added hacky 'connect' option that attempts to reconnect to internet. otherwise just checks internet connectivity with ping

diff --git a/bin/internet b/bin/internet
--- a/bin/internet
+++ b/bin/internet
@@ -1,24 +1,34 @@
 #!/bin/bash
 
-# make sure we're connected to the interwebz
-ping -w 1 -c 1 -q www.google.com &>/dev/null
+if [ "$1" == "-c" ]; then
 
-# if ping failed, try to reset internet connection
-if [ ! $? -eq 0 ]; then
+    # make sure we're connected to the interwebz
     ping -w 1 -c 1 -q www.google.com &>/dev/null
 
-    # Attempt internet reset 10 times
-    for i in {1..10}
-    do
-        ifdown eth0 &>/dev/null
-        timeout 6 ifup eth0 &>/dev/null
+    # if ping failed, try to reset internet connection
+    if [ ! $? -eq 0 ]; then
         ping -w 1 -c 1 -q www.google.com &>/dev/null
-        # exit successfully if we connected
-        if [ $? -eq 0 ]; then
-            exit 0
-        fi
-    done
 
-    # exit unsuccessfully if 10 resets couldn't connect
-    exit 1
+        # Attempt internet reset 10 times
+        for i in {1..10}
+        do
+            ifdown eth0 &>/dev/null
+            timeout 6 ifup eth0 &>/dev/null
+            ping -w 1 -c 1 -q www.google.com &>/dev/null
+            # exit successfully if we connected
+            if [ $? -eq 0 ]; then
+                exit 0
+            fi
+        done
+
+        # exit unsuccessfully if 10 resets couldn't connect
+        exit 1
+    fi
+else
+    ping -w 1 -c 1 -q www.google.com &>/dev/null
+    if [ ! $? -eq 0 ]; then
+        exit 1
+    else
+        exit 0
+    fi
 fi
